version: "3"
services:
  mozhi:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/version || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
