name: mozhi pipeline
on: push
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    name: Push Docker image to Codeberg docker registry
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install docker
        uses: papodaca/install-docker-action@main

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          username: aryak
          password: ${{ secrets.MOZHI_DOCKER_PASSWORD }}
          registry: codeberg.org
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: codeberg.org/aryak/mozhi:latest
