name: mozhi pipeline
on: push
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    name: Push Docker image to Codeberg docker registry
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          username: aryak
          password: ${{ secrets.MOZHI_DOCKER_PASSWORD }}
          registry: codeberg.org
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: latest
